os:
  - linux
  - osx
  - windows
sudo: false
language: cpp

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then tests/Debug/test.exe; else tests/test ;fi